language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t millerbyte/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true millerbyte/docker-react npm run test